
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    image: open-webui-frontend
    container_name: open-webui-frontend
    ports:
      - "3000:3000"  # Cambia este puerto según sea necesario
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENAI_API_KEY=tu_api_key
      - WEBUI_SECRET_KEY=tu_webui_secret_key # Asegúrate de establecer esta variable de entorno
      - ANONYMIZED_TELEMETRY=false
      - SCARF_NO_ANALYTICS=true
      - DO_NOT_TRACK=true
      - API_BASE_URL=http://backend:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: open-webui-backend
    container_name: open-webui-backend
    environment:
      - OPENAI_API_KEY=tu_api_key
      - WEBUI_SECRET_KEY=tu_webui_secret_key # Establecer esta variable de entorno
      - OLLAMA_BASE_URL=http://ollama:11434
      - WHISPER_MODEL="base"
      - WHISPER_MODEL_DIR="/app/backend/data/cache/whisper/models"
      - RAG_EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - RAG_RERANKING_MODEL=""
      - SENTENCE_TRANSFORMERS_HOME="/app/backend/data/cache/embedding/models"
      - HF_HOME="/app/backend/data/cache/embedding/models"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    tty: true
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    command: ["ollama", "run", "model_name"]  # Cambia 'model_name' por el que necesites

volumes:
  ollama: {}
