# Dockerfile para Frontend
FROM node:21-alpine3.19 AS frontend-build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# Usamos Nginx para servir los archivos del frontend
FROM nginx:alpine

COPY --from=frontend-build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
